### ISSUE TITLE
fix: mypy no-any-return in telegram_bot/bot.py:676

### ISSUE THREAD

**Issue by yastman** [yastman/rag#3003]
Pre-existing mypy failure introduced in #2963 (refactor/2963-miniapp-purge), confirmed by PR #3001 review (pr-review-opus).\n\n```\ntelegram_bot/bot.py:676: error: Returning Any from function declared to return "Message" [no-any-return]\n```\n\nFix: add explicit return type annotation or cast.\n\n**Source:** PR #3001 new_bugs_disposition follow_up_issue
