### ISSUE TITLE
fix(tests): test_memory.py fails under xdist (-n auto)

### ISSUE THREAD

**Issue by yastman** [yastman/rag#207]
## Problem

`tests/unit/integrations/test_memory.py::TestCreateRedisCheckpointer::test_returns_async_redis_saver` fails when running with `pytest -n auto` (xdist parallel mode), but passes in isolation.

**Error:** `AttributeError: module 'langgraph.checkpoint' has no attribute 'redis'`

The test uses `patch("langgraph.checkpoint.redis.aio.AsyncRedisSaver")` which requires the module to be importable. In xdist workers, the lazy namespace package `langgraph.checkpoint.redis` isn't properly initialized.

## Reproduce

```bash
# Fails:
uv run pytest tests/unit/integrations/test_memory.py -n auto -xvs

# Passes:
uv run pytest tests/unit/integrations/test_memory.py -xvs
```

## Possible Fixes

1. Add `pytest.importorskip("langgraph.checkpoint.redis")` before the patch
2. Use `@pytest.mark.skipif` if the module can't be imported
3. Import the module explicitly in the test to trigger namespace resolution before `patch()`

## Context

Blocking CI parallelization (`-n auto` would reduce test time from ~28 min to ~3 min).

**Comment by yastman** [comment]
Closing per maintainer backlog cleanup directive after full PR merge sweep on 2026-02-12. Reopen if this must stay tracked.
