### ISSUE TITLE
fix(bot): feedback scores may silently fail to write to Langfuse

### ISSUE THREAD

**Issue by yastman** [yastman/rag#277]
## Problem

User feedback (👍/👎) buttons appear on responses but scores may not reach Langfuse. The system silently swallows errors.

Originally implemented in PR #245 (issue #229, closed 2026-02-13).

### BUG 1 (Critical): `create_score` called outside `@observe` context
- **File:** `telegram_bot/bot.py:870-878`
- `handle_feedback()` is NOT decorated with `@observe`
- Calls `get_client().create_score(trace_id=...)` — Langfuse SDK v3 `get_client()` outside `@observe` may return a context object that doesn't properly proxy `create_score`
- Error swallowed by `except Exception` + `logger.debug` (line 879-880) — invisible in production logs

### BUG 2 (Medium): `trace_id` obtained before `propagate_attributes`
- **File:** `telegram_bot/bot.py:604-606` (text), `bot.py:710-712` (voice)
- `get_current_trace_id()` called BEFORE `propagate_attributes()` context entry
- Inside `@observe` so likely OK, but ordering is fragile

### BUG 3 (Low): Feedback buttons on CHITCHAT/OFF_TOPIC responses
- `respond_node` attaches feedback buttons to ALL responses including canned "Привет! 👋"
- Adds noise to feedback data

### Missing: No idempotency on feedback scores
- User can click button multiple times before confirmation replaces keyboard
- No `score_id` deduplication

### Missing: No integration test for handle_feedback with Langfuse
- Only unit tests for `parse_feedback_callback` and keyboard builder exist

## Steps to Reproduce

1. Send any query to the bot
2. Receive response with 👍/👎 buttons
3. Click 👍 or 👎
4. Check Langfuse traces — `user_feedback` score may be missing

## Expected Behavior

- Clicking feedback button MUST write `user_feedback` score (0.0/1.0) to the matching Langfuse trace
- Score must be visible in Langfuse UI linked to the correct trace
- Errors must be logged at WARNING level, not DEBUG

## Affected Files

- `telegram_bot/bot.py` (handle_feedback, trace_id injection)
- `telegram_bot/graph/nodes/respond.py` (feedback buttons on all responses)
- `telegram_bot/observability.py` (get_client usage pattern)

## Fix Plan

1. Use `get_langfuse_client()` (direct Langfuse SDK) instead of `get_client()` for `create_score` in `handle_feedback`
2. Move `trace_id` injection inside `propagate_attributes` block
3. Skip feedback buttons for CHITCHAT/OFF_TOPIC query types
4. Add `id` (idempotency key) to `create_score` call
5. Change error logging from DEBUG to WARNING
6. Add integration test for handle_feedback → Langfuse score

## Related

- #229 (original implementation, closed)
- PR #245 (merged)
- #233 (dataset management — depends on feedback data)
- #242 (unified traces)

**Comment by yastman** [comment]
## Deployment Checklist

After PR merged:
1. `docker compose build --no-cache bot` — пересобрать образ бота
2. `docker compose up -d --force-recreate bot` — поднять с новым образом
3. Проверить в Langfuse UI что `user_feedback` score пишется на trace после клика 👍/👎

### VPS
```bash
make k3s-push-bot && make k3s-bot
```

**Comment by yastman** [comment]
Status update (2026-02-17):

- Reviewed PR #278 (fix/feedback-langfuse-277) against issue scope.
- Verified Langfuse SDK behavior via docs (Context7 + Exa): for Python, idempotency key for create_score is score_id; create_score(trace_id=...) outside active observe context is supported.
- Current blocker to merge: new tests in PR fail locally due patch target resolution (patch("telegram_bot.bot...") before module attribute exists), causing AttributeError: module 'telegram_bot' has no attribute 'bot'.
- CI on PR is red (Lint & Type Check), and merge is not safe until tests/checks are green.

Next action to close #277: fix failing test patching pattern in PR #278 and rerun checks.
